Modified Files:  	CHANGELOG makesymlinks sysconfig/network-devices/ifdown  	sysconfig/network-devices/ifup
Added Files:
 	README sysconfig/network-devices/services/static

This allows the creation of scripts for setting up network interfaces.
Meant as a replacement for ifup-eth0 and ifdown-eth0.


git-svn-id: svn://svn.linuxfromscratch.org/LFS/trunk/bootscripts@3194 4aa44e1e-78dd-0310-a6d2-fbcd4c07a689

diff --git a/sysconfig/network-devices/ifdown b/sysconfig/network-devices/ifdown
--- a/sysconfig/network-devices/ifdown
+++ b/sysconfig/network-devices/ifdown
@@ -1,15 +1,26 @@
 #!/bin/sh
+# Begin $network_devices/ifdown
 
-source /etc/sysconfig/rc 
-source $rc_functions 
-source $network_devices/ifconfig.$1 
+# Written by Nathan Coulson <nathan@linuxfromscratch.org>
+. /etc/sysconfig/rc 
+. $rc_functions 
+. $network_devices/ifconfig.$1 
 
 if [ -f $network_devices/ifdown-$1 ]
 then
 	$network_devices/ifdown-$1
 else
-	echo "Bringing down the $1 interface..."
-	ifconfig $1 down
-	evaluate_retval
+	if [ -z $SERVICE ]
+	then
+		echo -n "SERVICE variable missing from ifconfig.$1, "
+		echo "using static"
+		SERVICE=static
+	fi
+	if [ ! -f $network_devices/script/$SERVICE ]
+	then
+		echo -n "Unknown Service: $SERVICE, cannot continue"
+		exit 1
+	fi
+	$network_devices/script/${SERVICE} $1 down
 fi
-
+# End $network_devices/ifdown
