boot_mesg() implementation
git-svn-id: svn://svn.linuxfromscratch.org/LFS/trunk@4260 4aa44e1e-78dd-0310-a6d2-fbcd4c07a689

diff --git a/bootscripts/lfs/init.d/checkfs b/bootscripts/lfs/init.d/checkfs
--- a/bootscripts/lfs/init.d/checkfs
+++ b/bootscripts/lfs/init.d/checkfs
@@ -16,96 +16,114 @@
 # 128  - Shared library error
 
 . /etc/sysconfig/rc
-. $rc_functions
+. ${rc_functions}
 
-case "$1" in
+case "${1}" in
 	start)
 		if [ -f /fastboot ]
 		then
-			boot_mesg "Fast boot requested, will not perform file system checks"
-			print_status warning
+			boot_mesg "/fastboot found, will not perform" ${INFO}
+			boot_mesg " file system checks as requested."
+			echo_ok
 			exit 0
 		fi
 
 		boot_mesg "Mounting root file system in read-only mode..."
-		mount -n -o remount,ro /
+		mount -n -o remount,ro / >/dev/null
 		evaluate_retval
 
-		if [ $? != 0 ]
+		if [ ${?} != 0 ]
 		then
-			print_status failure
-			boot_mesg "\nCannot check root filesystem because it could not" $FAILURE
-			boot_mesg " be mounted in read-only mode."
-			boot_mesg "\n\nWhen you press Enter, this system will be halted."
-			boot_mesg "\n\nPress enter to continue..." $NORMAL
+			echo_failure
+			boot_mesg "FAILURE:\n\nCannot check root" ${FAILURE}
+			boot_mesg " filesystem because it could not be mounted"
+			boot_mesg " in read-only mode.\n\nAfter you"
+			boot_mesg " press Enter, this system will be"
+			boot_mesg " halted and powered off."
+			boot_mesg "\n\nPress enter to continue..." ${INFO}
+			boot_mesg "" ${NORMAL}
 			read ENTER
-			halt -f
+			halt -d -f -i -p
 		fi
 
 		if [ -f /forcefsck ]
 		then
-			boot_mesg "/forcefsck exists, forcing file system check"
-			print_status warning
+			boot_mesg "/forcefsck found, forcing file" ${INFO}
+			boot_mesg " system checks as requested."
+			echo_ok
 			options="-f"
 		else
 			options=""
 		fi
 
 		boot_mesg "Checking file systems..."
-		#Note: -a option used to be -p; but this fails e.g. on fsck.minix
-		fsck $options -a -A -C -T
-		error_value=$?
+		# Note: -a option used to be -p; but this fails e.g.
+		# on fsck.minix
+		fsck ${options} -a -A -C -T 2>/dev/null
+		error_value=${?}
 
-		if [ "$error_value" = 1 ]
+		if [ "${error_value}" = 0 ]
 		then
-			boot_mesg "\nFile system errors were found and have been corrected." $WARNING
-			boot_mesg "  You may want to double-check that everything was fixed"
-			boot_mesg " properly"
+			echo_ok
+		fi
+
+		if [ "${error_value}" = 1 ]
+		then
+			echo_warning
+			boot_mesg "WARNING:\n\nFile system errors" ${WARNING}
+			boot_mesg " were found and have been corrected."
+			boot_mesg "  You may want to double-check that"
+			boot_mesg " everything was fixed properly."
 			boot_mesg "" $NORMAL
-			print_status warning
 		fi
 
-		if [ "$error_value" = 0 ]
+		if [ "${error_value}" = 2 -o "${error_value}" = 3 ]
 		then
-			print_status success
-		fi
-
-		if [ "$error_value" = 2 -o "$error_value" = 3 ]
-		then
-			print_status failure
-			boot_mesg "\nFile system errors were found and have been corrected, but" $WARNING
-			boot_mesg " the nature of the errors require this system to be rebooted."
-			boot_mesg "\n\nWhen you press enter, this system will be rebooted."
-			boot_mesg "\n\nPress Enter to continue..." $NORMAL
+			echo_warning
+			boot_mesg "WARNING:\n\nFile system errors" ${WARNING}
+			boot_mesg " were found and have been been"
+ 			boot_mesg " corrected, but the nature of the"
+			boot_mesg " errors require this system to be"
+			boot_mesg " rebooted.\n\nAfter you press enter,"
+			boot_mesg " this system will be rebooted"
+			boot_mesg "\n\nPress Enter to continue..." ${INFO}
+			boot_mesg "" ${NORMAL}
 			read ENTER
 			reboot -f
 		fi
 
-		if [ "$error_value" -gt 3 -a "$error_value" -lt 16 ]
+		if [ "${error_value}" -gt 3 -a "${error_value}" -lt 16 ]
 		then
-			print_status failure
-			boot_mesg "File system errors were encountered that couldn't be" $FAILURE
-			boot_mesg " fixed automatically.  This system cannot continue to boot"
-			boot_mesg " and will therefore be halted until those errors are fixed manually"
-			boot_mesg " by a System Administrator"
-			boot_mesg "\n\nWhen you press Enter, this system will be halted."
-			boot_mesg "\n\nPress Enter to continue..." $NORMAL
+			echo_failure
+			boot_mesg "FAILURE:\n\nFile system errors" ${FAILURE}
+			boot_mesg " were encountered that could not be"
+			boot_mesg " fixed automatically.  This system"
+			boot_mesg " cannot continue to boot and will"
+			boot_mesg " therefore be halted until those"
+			boot_mesg " errors are fixed manually by a"
+			boot_mesg " System Administrator.\n\nAfter you"
+			boot_mesg " press Enter, this system will be"
+			boot_mesg " halted and powered off."
+			boot_mesg "\n\nPress Enter to continue..." ${INFO}
+			boot_mesg "" ${NORMAL}
 			read ENTER
-			halt -f
+			halt -d -f -i -p
 		fi
 
-		if [ "$error_value" -ge 16 ]
-		then 
-			boot_mesg "\nUnexpected Failure running fsck. Exited with $error_value" $FAILURE
+		if [ "${error_value}" -ge 16 ]
+		then
+			echo_failure
+			boot_mesg "FAILURE:\n\nUnexpected Failure" ${FAILURE}
+			boot_mesg " running fsck.  Exited with error"
+			boot_mesg " code: ${error_value}."
 			boot_mesg "" $NORMAL
-			print_status failure
-			exit $error_value
+			exit ${error_value}
 		fi
 		;;
 	*)
-		echo "Usage: $0 {start}"
+		echo "Usage: ${0} {start}"
 		exit 1
 		;;
 esac
 
-# End $rc_base/init.d/checkfs
+# End $rc_base/in:nit.d/checkfs
