Return the status of pidofproc in statusproc
git-svn-id: svn://svn.linuxfromscratch.org/LFS/trunk@8074 4aa44e1e-78dd-0310-a6d2-fbcd4c07a689

diff --git a/bootscripts/lfs/init.d/functions b/bootscripts/lfs/init.d/functions
--- a/bootscripts/lfs/init.d/functions
+++ b/bootscripts/lfs/init.d/functions
@@ -281,6 +281,7 @@ statusproc()
 {
 	local pidfile=""
 	local base=""
+	local ret=""
 
 	while true
 	do
@@ -320,6 +321,9 @@ statusproc()
 		pidofproc -s -p "${pidfile}" "${1}"
 	fi
 
+	# Store the return status
+	ret=$?
+
 	if [ -n "${pidlist}" ];	then
 		${ECHO} -e "${INFO}${base} is running with Process"\
 			"ID(s) ${pidlist}.${NORMAL}"
@@ -336,6 +340,9 @@ statusproc()
 			fi
 		fi
 	fi
+
+	# Return the status from pidofproc
+	return $ret
 }
 
 # The below functions are documented in the LSB-generic 2.1.0
