Removed if{up,down}-eth0 compatibility, remove ASSUME SERVICE=static compatibility
git-svn-id: svn://svn.linuxfromscratch.org/LFS/trunk@3896 4aa44e1e-78dd-0310-a6d2-fbcd4c07a689

diff --git a/bootscripts/lfs/sysconfig/network-devices/ifup b/bootscripts/lfs/sysconfig/network-devices/ifup
--- a/bootscripts/lfs/sysconfig/network-devices/ifup
+++ b/bootscripts/lfs/sysconfig/network-devices/ifup
@@ -14,22 +14,16 @@ then
   exit 0
 fi
 
-if [ -f $network_devices/ifup-$1 ]
+if [ -z $SERVICE ]
 then
-	$network_devices/ifup-$1
-else
-	if [ -z $SERVICE ]
-	then
-		echo -n "SERVICE variable missing from ifconfig.$1, "
-		echo "using static"
-		SERVICE=static
-	fi
-	if [ ! -f $network_devices/services/$SERVICE ]
-	then
-		echo -n "Unknown Service: $SERVICE, cannot continue"
-		exit 1
-	fi
-	$network_devices/services/${SERVICE} $1 up
+	echo "SERVICE variable missing from ifconfig.$1, cannot continue"
+	exit 1
 fi
+if [ ! -f $network_devices/services/$SERVICE ]
+then
+	echo -n "Unknown Service: $SERVICE, cannot continue"
+	exit 1
+fi
+$network_devices/services/${SERVICE} $1 up
 
 # End $network_devices/ifup
