Added Kevin P. Fleming's PEER patch
git-svn-id: svn://svn.linuxfromscratch.org/LFS/trunk/bootscripts@3933 4aa44e1e-78dd-0310-a6d2-fbcd4c07a689

diff --git a/lfs/sysconfig/network-devices/services/ipv4-static b/lfs/sysconfig/network-devices/services/ipv4-static
--- a/lfs/sysconfig/network-devices/services/ipv4-static
+++ b/lfs/sysconfig/network-devices/services/ipv4-static
@@ -14,13 +14,19 @@ if [ -z "$IP" ]; then
 	exit 1
 fi
 
-if [ -z "$PREFIX" ]; then
+if [ -z "$PREFIX" -a -z "$PEER" ]; then
 	echo -n "PREFIX variable missing from $IFCONFIG, "
 	echo    "assuming 24"
 	PREFIX=24
+	args="$args $IP/$PREFIX"
+elif [ -n "$PREFIX" -a -n "$PEER" ]; then
+	echo "PREFIX and PEER both specified in $IFCONFIG, cannot continue"
+	exit 1
+elif [ -n "$PREFIX" ]; then
+	args="$args $IP/$PREFIX"
+elif [ -n "$PEER" ]; then
+	args="$args $IP peer $PEER"
 fi
-
-args="$args $IP/$PREFIX"
 
 if [ -n "$BROADCAST" ]; then
 	args="$args broadcast $BROADCAST"
