Applied DJ's loadproc/killproc/reloadproc/getpids patch
git-svn-id: svn://svn.linuxfromscratch.org/LFS/trunk/bootscripts@3976 4aa44e1e-78dd-0310-a6d2-fbcd4c07a689

diff --git a/lfs/init.d/functions b/lfs/init.d/functions
--- a/lfs/init.d/functions
+++ b/lfs/init.d/functions
@@ -7,7 +7,16 @@
 # With code based on Matthias Benkmann's simpleinit-msb @
 # http://winterdrache.de/linux/newboot/index.html
 
-# Number of seconds between term signal and kill signal when stopping processes
+# Initial Stop Signal
+STOPSIG=TERM
+
+# The fallback if STOPSIG does not stop a process in time (see KILLDELAY)
+FALLBACK=KILL
+
+# Signal sent to running processes to refresh their configuration
+RELOADSIG=HUP
+
+# Number of seconds between STOPSIG and FALLBACK when stopping processes
 KILLDELAY=3
 
 umask 022
@@ -36,68 +45,68 @@ FAILURE="\\033[1;31m"
 
 echo_ok()
 {
-        echo -e "$CURS_UP$SET_COL"["$SUCCESS""  OK  ""$NORMAL"]
+	echo -e "$CURS_UP$SET_COL"["$SUCCESS""  OK  ""$NORMAL"]
 }
 
 echo_failure()
 {
-        echo -e "$CURS_UP$SET_COL"["$FAILURE"FAILED"$NORMAL"]
+	echo -e "$CURS_UP$SET_COL"["$FAILURE"FAILED"$NORMAL"]
 }
 
 echo_warning()
 {
-        echo -e "$CURS_UP$SET_WCOL$@$SET_COL"["$WARNING" WARN  "$NORMAL"]
+	echo -e "$CURS_UP$SET_WCOL$@$SET_COL"["$WARNING" WARN  "$NORMAL"]
 }
 
 # $i is inherited by the rc script
 print_error_msg()
 {
 	echo -e -n $FAILURE
-        echo
-        echo "You should not be reading this error message. It means"
-        echo "that an unforseen error took place in $i,"
-        echo "which exited with a return value of $error_value"
-        echo
-        echo "If you're able to track this error down to a bug in one"
-        echo "of the files provided by the LFS book, please be so kind"
-        echo "to inform us at lfs-dev@linuxfromscratch.org"
+	echo
+	echo "You should not be reading this error message. It means"
+	echo "that an unforseen error took place in $i,"
+	echo "which exited with a return value of $error_value"
+	echo
+	echo "If you're able to track this error down to a bug in one"
+	echo "of the files provided by the LFS book, please be so kind"
+	echo "to inform us at lfs-dev@linuxfromscratch.org."
 	echo -e -n $NORMAL
-        echo
-        echo
-        echo "Press Enter to continue..."
-        read ENTER
+	echo
+	echo
+	echo "Press Enter to continue..."
+	read ENTER
 }
 
 # $i is inherited by the rc script
 check_script_status()
 {
-        if [ ! -f $i ]
-        then
-                echo "$i is not a valid symlink"
-                continue
-        fi
+	if [ ! -f $i ]
+	then
+		echo "$i is not a valid symlink"
+		continue
+	fi
 
-        if [ ! -x $i ]
-        then
-                echo "$i is not executable, skipping"
-                continue
-        fi
+	if [ ! -x $i ]
+	then
+		echo "$i is not executable, skipping"
+		continue
+	fi
 }
 
 evaluate_retval()
 {
-        error_value=$?
+	error_value=$?
 
-        if [ $error_value = 0 ]
-        then
-                print_status success
-        else
-                print_status failure
+	if [ $error_value = 0 ]
+	then
+		print_status success
+	else
+		print_status failure
 		sleep 5
-        fi
+	fi
 
-        return 0
-        #return $error_value
+	return 0
+	#return $error_value
 }
 
 print_status()
@@ -131,93 +140,72 @@ print_status()
 # Returns all of the pid #'s for $1 process
 getpids()
 {
-        base=${1##*/}
-        local lpids=""
-        local pid
+	base=${1##*/}
+	local lpids=""
+	local pid
 
-        pidlist=""
-        lpids=$(pidof $base)
-        for pid in $lpids
-        do
-                if [ $pid -ne $$ ] && [ $pid -ne $PPID ]
-                then
-                        pidlist="$pidlist $pid"
-                fi
-        done
+	pidlist=""
+	if [ -n "$PIDFILE" ]; then
+		lpids=$(cat $PIDFILE)
+	else
+		lpids=$(pidof $base)
+	fi
+
+	for pid in $lpids
+	do
+		if [ $pid -ne $$ ] && [ $pid -ne $PPID ]
+		then
+			pidlist="$pidlist $pid"
+		fi
+	done
 }
 
 # Starts a program if it is currently not running
 loadproc()
 {
-        if [ $# = 0 ]
-        then
-                echo "Usage: loadproc {program}"
-                exit 1
-        fi
+	if [ $# = 0 ]
+	then
+		echo "Usage: loadproc {program}"
+		exit 1
+		fi
 
-	if [ -n "$PIDFILE" -a -r "$PIDFILE" ]; then
-		pidlist=`cat $PIDFILE`
+	getpids $1
+
+	if [ -z "$pidlist" ]
+	then
+		"$@"
+		evaluate_retval
 	else
-		getpids $1
+		print_status warning running
 	fi
-
-        if [ -z "$pidlist" ]
-        then
-                "$@"
-                evaluate_retval
-        else
-                print_status warning running
-        fi
 }
 
 # Stops a process if it is running
 killproc()
 {
-	#If PIDFILE is set, no need to pass arguments
-	if [ -n "$PIDFILE" -a -r "$PIDFILE" ]; then
-		pidlist=`cat $PIDFILE`
-		if [ -z "$2" ]; then
-			signal=TERM
-			fallback=KILL
-		else
-			signal=${2##-}
-			signal=${signal##SIG}
-			fallback=""
-		fi
-	else
-		if [ ${#} = 0 ]; then
-			echo "Usage: killproc {program} [signal]"
-			exit 1
-		fi
-
-		if [ -z "$2" ]; then
-			signal=TERM
-			fallback=KILL
-		else
-			signal=${2##-}
-			signal=${signal##SIG}
-			fallback=""
-		fi
-
-		getpids $1
+	if [ -z "$PIDFILE" -a -z "$#" ]; then
+		echo "Usage: killproc [{program}]"
+		exit 1	
 	fi
+
+	getpids "$1"
 
 	if [ -n "$pidlist" ]; then
 		local i=0
 		for pid in $pidlist; do
-			kill -$signal $pid 2>/dev/null
+			kill -$STOPSIG $pid 2>/dev/null
 			while [ $i -lt $KILLDELAY ]; do
 				kill -0 $pid 2>/dev/null || break
 				sleep 1
 				i=$(($i+1))
 			done
 
-			if [ -n "$fallback" ]; then
-				kill -$fallback $pid 2>/dev/null
+			if [ -n "$FALLBACK" ]; then
+				kill -$FALLBACK $pid 2>/dev/null
 			fi
 		done
 
-		getpids $1
+		getpids "$1"
 
 		base=${1##*/}
 
@@ -225,7 +213,7 @@ killproc()
 			failure=1
 		else
 			failure=0
-			if [ ! -z $PIDFILE ]; then
+			if [ -n "$PIDFILE" ]; then
 				rm -f $PIDFILE
 			else
 				rm -f /var/run/$base.pid
@@ -241,29 +229,21 @@ killproc()
 
 reloadproc()
 {
-        if [ $# = 0 ]
-        then
-                echo "Usage: reloadproc {program} [signal]"
-                exit 1
-        fi
+	if [ $# = 0 ]
+	then
+		echo "Usage: reloadproc [{program}]"
+		exit 1
+	fi
 
-        if [ -z "$2" ]; then
-                signal=HUP
-        else
-                signal=${2##-}
-                signal=${signal##SIG}
+	getpids $1
 
-        fi
-
-        getpids $1
-
-        if [ -n "$pidlist" ]
-        then
-                failure=0
+	if [ -n "$pidlist" ]
+	then
+		failure=0
 
                 for pid in $pidlist
                 do
-                        kill -$signal $pid || failure=1
+                        kill -$RELOADSIG $pid || failure=1
                 done
 
                 (exit $failure)
