Disabled the logging until further notice.  It prevented / from getting remounted ro, as it was connected to /var/log/boot.log
git-svn-id: svn://svn.linuxfromscratch.org/LFS/trunk/bootscripts@3751 4aa44e1e-78dd-0310-a6d2-fbcd4c07a689

diff --git a/lfs/init.d/rc b/lfs/init.d/rc
--- a/lfs/init.d/rc
+++ b/lfs/init.d/rc
@@ -7,11 +7,13 @@
 . /etc/sysconfig/rc
 . $rc_functions
 
-# Function used for logging
+# Function used for logging, reports unable to write errors with the test,
+# and fails to allow / to be mounted ro on shutdown.  It is not suggested
+# for use yet.
 logboot()
 {
-	if [ -w "/var/log/boot.log" ]; then
-		( "$@" | tee /var/log/boot.log && exit $PIPESTATUS )
+	if echo -n >> /var/log/boot.log; then
+		( "$@" | tee -a /var/log/boot.log && exit $PIPESTATUS )
 	else
 		"$@"
 	fi
@@ -27,7 +29,7 @@ trap "" INT QUIT TSTP
 
 if [ "$runlevel" = "" ]
 then
-        logboot echo "Usage: $0 <runlevel>" >&2
+        echo "Usage: $0 <runlevel>" >&2
         exit 1
 fi
 
@@ -36,7 +38,7 @@ previous=$PREVLEVEL
 
 if [ ! -d $rc_base/rc$runlevel.d ]
 then
-        logboot echo "$rc_base/rc$runlevel.d does not exist"
+        echo "$rc_base/rc$runlevel.d does not exist"
         exit 1
 fi
 
@@ -57,21 +59,19 @@ then
                 then
                         if [ ! -f $prev_start ] && [ ! -f $sysinit_start ]
                         then
-                                logboot echo -n -e $WARNING
-                                logboot echo "$i can't be executed because it was"
-                                logboot echo "not started in the previous runlevel ($previous)"
-                                logboot echo -n -e $NORMAL
+                                echo -n -e $WARNING
+                                echo "$i can't be executed because it was"
+                                echo "not started in the previous runlevel ($previous)"
+                                echo -n -e $NORMAL
                                 continue
                         fi
                 fi
-                logboot echo -n "$i stop:"
-                logboot $i stop
-                logboot echo
+                $i stop
                 error_value=$?
 
                 if [ "$error_value" != "0" ]
                 then
-                        logboot print_error_msg
+                        print_error_msg
                 fi
         done
 fi
@@ -91,14 +91,14 @@ do
         check_script_status
 
 	case $runlevel in
-                0|6) logboot echo -n "$i stop:"  && logboot $i stop	;;
-		*)   logboot echo -n "$i start:" && logboot $i start	;;
+                0|6) $i stop	;;
+		*)   $i start	;;
 	esac
         error_value=$?
 
         if [ "$error_value" != "0" ]
         then
-                logboot print_error_msg
+                print_error_msg
         fi
 done
 
