All scripts have been converted to boot_mesg
git-svn-id: svn://svn.linuxfromscratch.org/LFS/trunk/bootscripts@4196 4aa44e1e-78dd-0310-a6d2-fbcd4c07a689

diff --git a/lfs/init.d/rc b/lfs/init.d/rc
--- a/lfs/init.d/rc
+++ b/lfs/init.d/rc
@@ -17,8 +17,8 @@ trap "" INT QUIT TSTP
 
 if [ "$runlevel" = "" ]
 then
-        echo "Usage: $0 <runlevel>" >&2
-        exit 1
+	echo "Usage: $0 <runlevel>" >&2
+	exit 1
 fi
 
 previous=$PREVLEVEL
@@ -26,68 +26,62 @@ previous=$PREVLEVEL
 
 if [ ! -d $rc_base/rc$runlevel.d ]
 then
-        echo "$rc_base/rc$runlevel.d does not exist"
-        exit 1
+	echo "$rc_base/rc$runlevel.d does not exist"
+	exit 1
 fi
 
 # Attempt to stop all service started by previous runlevel,
 # and killed in this runlevel
 if [ "$previous" != "N" ]
 then
-        for i in $(ls -v $rc_base/rc$runlevel.d/K* 2> /dev/null)
-        do
+	for i in $(ls -v $rc_base/rc$runlevel.d/K* 2> /dev/null); do
+		check_script_status
 
-                check_script_status
+		suffix=${i#$rc_base/rc$runlevel.d/K[0-9][0-9]}
+		prev_start=$rc_base/rc$previous.d/S[0-9][0-9]$suffix
+		sysinit_start=$rc_base/rcsysinit.d/S[0-9][0-9]$suffix
 
-                suffix=${i#$rc_base/rc$runlevel.d/K[0-9][0-9]}
-                prev_start=$rc_base/rc$previous.d/S[0-9][0-9]$suffix
-                sysinit_start=$rc_base/rcsysinit.d/S[0-9][0-9]$suffix
+		if [ "$runlevel" != "0" ] && [ "$runlevel" != "6" ]; then
+			if [ ! -f $prev_start ] && [ ! -f $sysinit_start ]; then
+				boot_log "$i cant be started in runlevel ${runlevel}, because it was not started in runlevel ${previous}"
+				echo -n -e $WARNING
+				echo "$i can't be executed because it was"
+				echo "not started in the previous runlevel ($previous)"
+				echo -n -e $NORMAL
+				continue
+			fi
+		fi
+		$i stop
+		error_value=$?
 
-                if [ "$runlevel" != "0" ] && [ "$runlevel" != "6" ]
-                then
-                        if [ ! -f $prev_start ] && [ ! -f $sysinit_start ]
-                        then
-                                echo -n -e $WARNING
-                                echo "$i can't be executed because it was"
-                                echo "not started in the previous runlevel ($previous)"
-                                echo -n -e $NORMAL
-                                continue
-                        fi
-                fi
-                $i stop
-                error_value=$?
-
-                if [ "$error_value" != "0" ]
-                then
-                        print_error_msg
-                fi
-        done
+		if [ "$error_value" != "0" ]
+		then
+			print_error_msg
+		fi
+	done
 fi
 
 #Start all functions in this runlevel
-for i in $( ls -v $rc_base/rc$runlevel.d/S* 2> /dev/null)
-do
-        if [ "$previous" != "N" ]
-        then
-                suffix=${i#$rc_base/rc$runlevel.d/S[0-9][0-9]}
-                stop=$rc_base/rc$runlevel.d/K[0-9][0-9]$suffix
-                prev_start=$rc_base/rc$previous.d/S[0-9][0-9]$suffix
+for i in $( ls -v $rc_base/rc$runlevel.d/S* 2> /dev/null); do
+	if [ "$previous" != "N" ]; then
+		suffix=${i#$rc_base/rc$runlevel.d/S[0-9][0-9]}
+		stop=$rc_base/rc$runlevel.d/K[0-9][0-9]$suffix
+		prev_start=$rc_base/rc$previous.d/S[0-9][0-9]$suffix
 
-                [ -f $prev_start ] && [ ! -f $stop ] && continue
-        fi
+		[ -f $prev_start ] && [ ! -f $stop ] && continue
+	fi
 
-        check_script_status
+	check_script_status
 
 	case $runlevel in
-                0|6) $i stop	;;
+		0|6) $i stop	;;
 		*)   $i start	;;
 	esac
-        error_value=$?
+	error_value=$?
 
-        if [ "$error_value" != "0" ]
-        then
-                print_error_msg
-        fi
+	if [ "$error_value" != "0" ]; then
+		print_error_msg
+	fi
 done
 
 # End $rc_base/init.d/rc
