Added additional error checking to the udev bootscript
git-svn-id: svn://svn.linuxfromscratch.org/LFS/trunk/bootscripts@3891 4aa44e1e-78dd-0310-a6d2-fbcd4c07a689

diff --git a/lfs/init.d/udev b/lfs/init.d/udev
--- a/lfs/init.d/udev
+++ b/lfs/init.d/udev
@@ -34,6 +34,21 @@ case "$1" in
 		# The reason we don't write to mtab is because we don't ever
 		# want /dev to be unavailable (such as by `umount -a').
 		mount -n -t ramfs ramfs /dev
+		if [ $? != 0 ]
+		then
+			print_status failure
+			echo -n -e $FAILURE
+			echo
+			echo "Cannot mount a ramfs onto /dev, this system will be halted."
+			echo
+			echo -n "When you press Enter, this system will be halted."
+			echo -n -e $NORMAL
+			echo
+			echo "Press Enter to continue..."
+			read ENTER
+
+			halt -f
+		fi
 
 		# Assign udev to get hotplug events.  This will be overwritten
 		# in the hotplug bootscript.
