removed consolelog and updated interactive contribs
git-svn-id: svn://svn.linuxfromscratch.org/LFS/trunk@6180 4aa44e1e-78dd-0310-a6d2-fbcd4c07a689

diff --git a/bootscripts/contrib/init.d/rc-Interactive b/bootscripts/contrib/init.d/rc-Interactive
--- a/bootscripts/contrib/init.d/rc-Interactive
+++ b/bootscripts/contrib/init.d/rc-Interactive
@@ -22,8 +22,17 @@ stty sane
 trap "" INT QUIT TSTP
 
 [ "${1}" != "" ] && runlevel=${1}
+export runlevel
 
-if [ "${runlevel}" = "" ]; then
+# Begin addition for tmpfs
+#export BOOTLOGCACHE=""
+if [ "${runlevel}" = "sysinit" ]; then
+	mount -n -t tmpfs tmpfs /media/boottemp -o mode=600
+fi
+# End addition for tmpfs
+
+if [ "${runlevel}" = "" ]
+then
 	echo "Usage: ${0} <runlevel>" >&2
 	exit 1
 fi
@@ -32,8 +41,8 @@ previous=${PREVLEVEL}
 [ "${previous}" = "" ] && previous=N
 
 # Begin addition for interactive starup.
-if [ "${runlevel}" != "sysinit" -a -f /tmp/.interactive-start ]; then
-	. /tmp/.interactive-start
+if [ "${runlevel}" != "sysinit" -a -f /media/boottemp/.interactive-start ]; then
+	. /media/boottemp/.interactive-start
 fi
 
 if [ "${INTERACTIVE}" == "I" -a "${runlevel}" != "sysinit" -a \
@@ -55,11 +64,13 @@ if [ "${runlevel}" == "sysinit" -a "${IPROMPT}" == "yes" ]; then
 		# Okay..we are using bash for the shell
 		# so -t and -n are okay for read
 		echo ""
-		# PTAB is the amount of spaces needed to format the message
+		# DTAB is the amount of spaces needed to format the message
 		# on the screen correctly.
-		echo -e "\\033[${PTAB}G""Welcome to ${INFO}${DISTRO}"
+		DTAB=$(( $(( ${COLUMNS} - ${DLEN} )) / 2 ))
+		echo -e "\\033[${DTAB}G""Welcome to ${INFO}${DISTRO}"
+		ITAB=$(( $(( ${COLUMNS} - ${ILEN} )) / 2 ))
 		# The "Press 'I'" message is broken in two for readability here
-		echo -n -e "\\033[18G""${NORMAL}Press '${FAILURE}I${NORMAL}'"
+		echo -n -e "\\033[${ITAB}G""${NORMAL}Press '${FAILURE}I${NORMAL}'"
 		echo -e " to enter interactive startup"
 		echo ""
 		read -t ${ITIME} -n 1 INTERACTIVE 2> /dev/null
@@ -75,7 +86,8 @@ fi
 
 # End addition for interactive startup
 
-if [ ! -d ${rc_base}/rc${runlevel}.d ]; then
+if [ ! -d ${rc_base}/rc${runlevel}.d ]
+then
 	boot_mesg "${rc_base}/rc${runlevel}.d does not exist." ${WARNING}
 	boot_mesg_flush
 	exit 1
@@ -83,7 +95,8 @@ fi
 
 # Attempt to stop all service started by previous runlevel,
 # and killed in this runlevel
-if [ "${previous}" != "N" ]; then
+if [ "${previous}" != "N" ]
+then
 	for i in $(ls -v ${rc_base}/rc${runlevel}.d/K* 2> /dev/null)
 	do
 		check_script_status
@@ -92,8 +105,10 @@ if [ "${previous}" != "N" ]; then
 		prev_start=$rc_base/rc$previous.d/S[0-9][0-9]$suffix
 		sysinit_start=$rc_base/rcsysinit.d/S[0-9][0-9]$suffix
 
-		if [ "${runlevel}" != "0" ] && [ "${runlevel}" != "6" ]; then
-			if [ ! -f ${prev_start} ] && [ ! -f ${sysinit_start} ]; then
+		if [ "${runlevel}" != "0" ] && [ "${runlevel}" != "6" ]
+		then
+			if [ ! -f ${prev_start} ] && [ ! -f ${sysinit_start} ]
+			then
 				boot_log "${i} cant be started in runlevel ${runlevel}, because it was not started in runlevel ${previous}"
 				boot_mesg -n "WARNING:\n\n${i} can't be" ${WARNING}
 				boot_mesg -n " executed because it was not"
@@ -107,7 +122,8 @@ if [ "${previous}" != "N" ]; then
 		${i} stop
 		error_value=${?}
 
-		if [ "${error_value}" != "0" ]; then
+		if [ "${error_value}" != "0" ]
+		then
 			print_error_msg
 		fi
 	done
@@ -116,7 +132,8 @@ fi
 #Start all functions in this runlevel
 for i in $( ls -v ${rc_base}/rc${runlevel}.d/S* 2> /dev/null)
 do
-	if [ "${previous}" != "N" ]; then
+	if [ "${previous}" != "N" ]
+	then
 		suffix=${i#$rc_base/rc$runlevel.d/S[0-9][0-9]}
 		stop=$rc_base/rc$runlevel.d/K[0-9][0-9]$suffix
 		prev_start=$rc_base/rc$previous.d/S[0-9][0-9]$suffix
@@ -163,29 +180,39 @@ do
 	esac
 	error_value=${?}
 
-	if [ "${error_value}" != "0" ]; then
+	if [ "${error_value}" != "0" ]
+	then
 		print_error_msg
 	fi
+
 done
 
 # Begin addition #3 for interactive starup
 if [ "${INTERACTIVE}" == "I" ]; then
 	# Insert check for writeable /tmp here
-	echo "INTERACTIVE='I'" > /tmp/.interactive-start 2> /dev/null
-	if [ "${?}" != "0" ]; then
-		# There is nothing we can do to make the next runlevel
-		# check for interactivity because /tmp is not writeable.
-		echo ""
-		echo -e "${WARNING}/tmp is not writable!!!"
-		echo -n -e "${WARNING}Interactive startup will not work"
-		echo -e "${WARNING} for the next runlevel!!!"
-		echo -e "${NORMAL}"
-		sleep 5
-	fi
+	echo "INTERACTIVE='I'" > /media/boottemp/.interactive-start 2> /dev/null
 else 
 	# Clear any existing file
-	rm -f /tmp/.interactive-start 2>&1 > /dev/null
+	rm -f /media/boottemp/.interactive-start 2>&1 > /dev/null
 fi
 # End addition #3 for interactive startup
+
+# Begin addition for inital bootlog
+if [ "${runlevel}" = "sysinit" ]; then
+	BTIMESPEC=$(echo `date +"%b %d %T"` `hostname`)
+	cat /media/boottemp/.logcache | sed "s@bootlog:@${BTIMESPEC} bootlog:@g" >> /var/log/boot.log
+	rm -f /media/boottemp/.logcache
+fi
+# End addition for inital bootlog
+
+# Begin addition for tmpfs
+if [ "${runlevel}" != "sysinit" ]; then
+	# Check to see if our temporary filesystem is mounted
+	mount | grep boottemp 2>&1 > /dev/null
+	if [ "$?" -eq "0" ]; then
+		umount /media/boottemp
+	fi
+fi
+# End addition for tempfs
 
 # End $rc_base/init.d/rc
