Added some changes made by Zack, added better error checking to mountfs.
git-svn-id: svn://svn.linuxfromscratch.org/LFS/trunk@3399 4aa44e1e-78dd-0310-a6d2-fbcd4c07a689

diff --git a/bootscripts/contrib/init.d/udev b/bootscripts/contrib/init.d/udev
--- a/bootscripts/contrib/init.d/udev
+++ b/bootscripts/contrib/init.d/udev
@@ -1,12 +1,16 @@
 #!/bin/sh
-# Begin $rc_base/init.d/udev
+# Begin $rc_base/init.d/udev - Udev cold-plugging script
 
-# Content by Zack Winkles  - winkie@linuxfromscratch.org
+# Written by Zack Winkles  - winkie@linuxfromscratch.org
 
 . /etc/sysconfig/rc
 . $rc_functions
 
-# Some things sysfs just doesn't export for us.
+# Assure that sysfs is mounted and that udev is present.
+[ -d /sys/block -a -x /sbin/udev ] || exit 0
+
+# Create some things that sysfs does not, and should not export for us.  Feel
+# free to add devices to this list.
 make_extra_nodes() {
 	ln -s /proc/self/fd /dev/fd
 	ln -s /proc/self/fd/0 /dev/stdin
@@ -19,17 +23,30 @@ make_extra_nodes() {
 
 case "$1" in
 	start)
-		# Assure that udev is the hotplug handler, as the book
-		# doesn't install full hotplug.
-		echo "/sbin/udev" > /proc/sys/kernel/hotplug
+		# When the hotplug package isn't installed, make sure that udev
+		# still gets hotplug events.
+		if [ ! -x /sbin/hotplug ]; then
+			echo /sbin/udev > /proc/sys/kernel/hotplug
+		fi
 
 		echo "Populating /dev with device nodes..."
+
+		# Mount a temporary file system over /dev, so that any devices
+		# made or removed during this boot don't affect the next one.
+		# The reason we don't write to mtab is because we don't ever
+		# want /dev to be unavailable (such as by `umount -a').
 		mount -n -t ramfs ramfs /dev
+
+		# Populate /dev with all the devices that are already available,
+		# and save it's status so we can report failures.
 		udevstart || failed=1
+
+		# Now, create some required files/directories/devices that sysfs
+		# doesn't export for us.
 		make_extra_nodes
 
-		# If $failed is empty, then the subshell exits with 0,
-		# otherwise 1, so it's good for status checking.
+		# When reporting the status, base it on the success or failure
+		# of the `udevstart' command, since that's the most important.
 		(exit $failed)
 		evaluate_retval
 		;;
